config/routes.rb
ColumbiaRepairReportPlatform::Application.routes.draw do
  resources :reports
  # map '/' to be a redirect to '/reports'
  root :to => 'pages#home'

  get 'report/:id/complete', to: 'reports#complete', as: :complete_report
  post 'report/:id/comment', to:'reports#addcmt', as: :addcmt_report

  # routes for qrcode
  get 'qrcode', to: 'pages#qrcode_generate', as: 'qrcode'
  get 'qrcode_download', to: 'pages#qrcode_download', as: 'qrcode_download'

  # manager routes
  resources :managers, only: [:new, :create, :edit, :update, :show, :destroy]

  # session routes
  get '/login', to: 'sessions#login', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  post '/logout', to: 'sessions#destroy'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :manager
    belongs_to :report
end

app/models/manager.rb
class Manager < ActiveRecord::Base
    has_many :comments
    has_secure_password
end

app/models/report.rb
class Report < ActiveRecord::Base
    has_many :comments
    mount_uploader :file, FileUploader
    def self.problemlist
        return ['Carpentry', 'Electronic','Floor','Furniture','Laundry','Mechanical','Pest Control','Housekeeping','Heating/Air Conditioning', 'Plumbing', 'Other']
    end

    def self.check_and_create(report_params)
        if Report.where(building: report_params[:building], area: report_params[:area]).take.nil?
            report_params[:status] = "Uncompleted"
            Report.create!(report_params.except!(:uni))
            return "successfully published"
        else
            return "Already been published"
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to login_path unless current_user
  end

  def current_user
    @current_user ||=
      begin
        return nil unless session[:manager_id]

        Manager.find(session[:manager_id])
      end
  end
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController

    def new
        @manager = Manager.new
    end

    def create
        # check if email is lionmail
        if !ManagersHelper.lionmail?(params[:manager][:email])
            message = "Please use your lionmail."
            return redirect_to new_manager_path, notice: message
        end
        # check if accout exists
        @manager = Manager.find_by(email: params[:manager][:email])
        if @manager
            message = "Account exists. Please try again."
            return redirect_to new_manager_path, notice: message
        end
        # check if passwords are valid and match
        @manager = Manager.new(manager_params)
        if @manager.save
            session[:manager_id] = @manager.id
            return redirect_to reports_path
        else
            message = "Invalid password. Please try again."
            return redirect_to new_manager_path, notice: message
        end
    end

    def show
        # @manager = Manager.find(params[:manager_id])
    end

    private

    def manager_params
        params.require(:manager).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home; end
    
    def qrcode_generate; end
  
    def qrcode_download
        # https://mighty-brushlands-39335.herokuapp.com
        # http://localhost:3000
        building = params[:report][:building]
        area = params[:report][:area]
        url = 'https://mighty-brushlands-39335.herokuapp.com%s' % [new_report_path(:report => {:building => building, :area => area})]
        fn = '%s_%s_qrcode.png' % [building.downcase, area.downcase]
        send_data RQRCode::QRCode.new(url).as_png(size: 300), type: 'image/png', filename: fn, disposition: 'attachment'
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]

  def show
    id = params[:id] # retrieve report ID from URI route
    @report = Report.find(id) # look up report by unique ID
    # will render app/views/reports/show.<extension> by default
  end

  def index
    @completed_checked = params[:show_complete]
    @emer_only_checked = params[:emer_only]
    if params[:problem_type].nil?
      params[:problem_type] = Hash.new
      params[:problem_type][:problem_type] = "All"
    end
    @selected = params[:problem_type][:problem_type]
      

    @problemlist = Report.problemlist.prepend("All")

    @reports = Report.where(status: "Uncompleted")

    if !params[:show_complete].nil?
      @reports = Report
    end

    if !params[:emer_only].nil?
      @reports = @reports.where(emergencylevel: "Urgent")
    end

    if @reports == Report
      @reports = Report.all
    end

    if !params[:problem_type].nil? && params[:problem_type][:problem_type] != "All"
      @reports = @reports.where(problemtype: params[:problem_type][:problem_type])
    end

    session[:emer_only]=params[:emer_only]
    session[:show_complete] = params[:show_complete]
  end

  def new
    @problemlist = Report.problemlist
    @prefilled_building = ''
    @prefilled_area = ''
    if params[:report] != nil
      building = params[:report][:building]
      area = params[:report][:area]
      @prefilled_building = building if building != nil
      @prefilled_area = area if area != nil
    end
  end

  def create
    if ReportsHelper.valid_uni?(report_params[:uni])
      flash[:notice] = Report.check_and_create(report_params)
    else
      flash[:notice] = "invalid UNI"
    end

    redirect_to root_path
  end

  def edit
    @report = Report.find params[:id]
  end

  def complete
    report = Report.find params[:id]
    flash[:notice] = "Marked as complete successful"
    report.status = "Completed"
    report.save
    redirect_to report_path(report)
  end

  def addcmt
    report = Report.find params[:id]
    if params[:comment][:cmt].blank?
      flash[:notice] = "Cannot add a blank comment"
    else 
      flash[:notice] = "Comment successfully added"
      report.comments.build(:comment => params[:comment][:cmt], :manager_id=>session[:manager_id])
      report.save
    end 
    redirect_to report_path(report)
  end

  def update
    @report = Report.find params[:id]
    @report.update_attributes!(report_params)
    flash[:notice] = "#{@report.id} was successfully updated."
    redirect_to report_path(@report)
  end

  def destroy
    # @report = Report.find(params[:id])
    # @report.destroy
    # flash[:notice] = "Report '#{@report.id}' completed."
    # redirect_to reports_path
  end

  private
  # Making "internal" methods private is not required, but is a common practice.
  # This helps make clear which methods respond to requests, and which ones do not.
  def report_params
    params.require(:report).permit(:building, :area, :problemtype, :emergencylevel, :uni, :description, :file)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def create
        @manager = Manager.find_by(email: params[:manager][:email])

        if !!@manager && @manager.authenticate(params[:manager][:password])
            session[:manager_id] = @manager.id
            redirect_to reports_path
        else
            message = "Invalid email/password"
            redirect_to login_path, notice: message
        end
    end

    def destroy
        session[:manager_id] = nil

        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in?
        session[:manager_id]
    end
end

app/helpers/managers_helper.rb
module ManagersHelper
    def self.lionmail?(email)
        email.match?(/^[a-z][a-z][0-9][0-9][0-9][0-9]@columbia.edu$/x) or email.match?(/^[a-z][a-z][a-z][0-9][0-9][0-9][0-9]@columbia.edu$/x)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def self.valid_uni?(uni)
    uni.match?(/^[a-z][a-z][0-9][0-9][0-9][0-9]$/x) or uni.match?(/^[a-z][a-z][a-z][0-9][0-9][0-9][0-9]$/x)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_flash.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="notice">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger" role="alert" id="warning">
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<%# Our "base" layout should be a valid HTML document. %>
<!DOCTYPE html>
<html>
  <head>
    <title>Columbia Repair Report Platform!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', 'media' => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# These classes come from the Bootstrap CSS framework. %>
    <nav class="navbar navbar-expand-lg mb-3">

      <% if logged_in? %>
        <a href="<%= reports_path %>">
          <img src="/assets/logo.png" style="width:480px;height:80px;"/>
        </a>
      <% else %>
        <a href="<%= root_path %>">
          <img src="/assets/logo.png" style="width:480px;height:80px;"/>
        </a>
      <% end %>

      <%= link_to 'Log Out', logout_path, :class => 'ml-auto btn btn-columbia' if logged_in? %>
    </nav>
    <div class="container">
      <%# Render "flash" messages in our application. This loads _flash.erb %>
      <%= render 'layouts/flash' %>
      <main id="main">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/managers/new.html.erb
<h2 class="text-columbia">Sign Up</h2>

<%= form_tag managers_path, :class => 'form', :id => 'form' do %>
  <%= label :manager, :name, 'Name', :class => 'col-form-label' %>
  <%= text_field :manager, :name, :class => 'form-control' %>
  <%= label :manager, :email, 'Email', :class => 'col-form-label' %>
  <%= text_field :manager, :email, :class => 'form-control' %>
  <%= label :manager, :password, 'Password', :class => 'col-form-label' %>
  <%= password_field :manager, :password, :class => 'form-control' %>
  <%= label :manager, :password_confirmation, 'Confirm Password', :class => 'col-form-label' %>
  <%= password_field :manager, :password_confirmation, :class => 'form-control' %>
  <br/>
  <%= submit_tag 'Sign Up', :class => 'btn btn-columbia' %>
<% end %>

app/views/pages/home.html.erb
<!-- app/views/pages/home.html.erb -->



<div class="center-screen">
  <h1 class="text-columbia"> Welcome! </h1>
  <br>
  <div class="display-inline">
    <%= link_to 'Submit a Report', new_report_path, :class => 'btn btn-columbia col-4' %>
    <%= link_to 'Manager Login', login_path, :class => 'btn btn-columbia col-4' %>
  </div>
</div>

app/views/pages/qrcode_generate.html.erb
<!-- app/views/pages/qr_code_generate.html.erb -->
<!-- referece: https://dev.to/collimarco/building-a-qr-code-generator-with-ruby-on-rails-28ki -->

<h2 class="text-columbia">QR Code Generator</h2>

<%= form_tag qrcode_download_path, :method => :get, :class => 'form', :id => 'form' do %>
  <%= label :report, :building, 'Location: Building', :class => 'col-form-label' %>
  <%= text_field :report, :building, :class => 'form-control' %>
  <%= label :report, :area, 'Location: Area', :class => 'col-form-label' %>
  <%= text_field :report, :area, :class => 'form-control' %>
  <br/>
  <%= submit_tag 'Generate', :class => 'btn btn-columbia' %>
  <%= link_to 'Cancel', reports_path, :class => 'btn btn-secondary' %>
<% end %>

app/views/reports/edit.html.erb
<h2 class="text-columbia">Manage Current Report</h2>

<%= form_tag report_path(@report), :method => :put, :multipart => true, :id => 'form' do %>
  <%= label :report, :building, 'Location: Building', :class => 'col-form-label' %>
  <%= text_field :report, :building, :class => 'form-control' %>
  <%= label :report, :area, 'Location: Area', :class => 'col-form-label' %>
  <%= text_field :report, :area, :class => 'form-control' %>
  <%= label :report, :problemtype, 'Problem Type', :class => 'col-form-label'%>
  <%= select :report, :problemtype, ['Carpentry', 'Electronic','Floor','Furniture','Laundry','Mechanical','Pest Control','Housekeeping','Heating/Air Conditioning', 'Plumbing', 'Other'], {}, {:class => 'form-control col-3'} %>
  <%= label :report, :emergencylevel, 'Emergency Level', :class => 'col-form-label'  %>
  <%= select :report, :emergencylevel, ['Emergent','Ordinary'], {}, {:class => 'form-control col-3'} %>
  <%= label :report, :description, 'Description', :class => 'col-form-label' %>
  <%= text_area :report, :description, :class => 'form-control' %>
  <%= label :report, :file, 'Image', :class => 'col-form-label' %>
  <%= file_field :report, :file, :class => 'form-control' %>
  <br/>
  <%= submit_tag 'Update Report Info', :class => 'btn btn-columbia' %>
  <%= link_to 'Cancel', report_path(@report), :class => 'btn btn-secondary' %>
<% end %>

app/views/reports/index.html.erb
<!--  This file is app/views/reports/index.html.erb -->


<h2 class="text-columbia">ALL Existing Reports</h2>

<h5 class="text-columbia"> Filters: </h5>

<%= form_tag reports_path, method: :get, id: 'form' do %>
  <div class="form-check  form-check-inline">
    <%= label_tag "emer_only", "Show Urgent Reports Only", class: 'form-check-label' %>
    <%= check_box_tag "emer_only", "1",  @emer_only_checked, class: 'form-check-input' %>
  </div>
  <div class="form-check  form-check-inline">
    <%= label_tag "show_complete", "Show Completed Reports", class: 'form-check-label' %>
    <%= check_box_tag "show_complete", "1",  @completed_checked, class: 'form-check-input' %>
  </div>
  <div class="form-row">
    <%= label "problem_type", "problem_type", 'Problem Type', :class => 'col-form-label'%>
    <div class="col-sm-3">
      <%= select "problem_type", "problem_type", @problemlist, {:selected=>@selected}, :class => 'form-control' %>
    </div>
  </div>
  <%= submit_tag 'Filter', id: 'filter_submit', class: 'btn btn-columbia' %>
<% end %>
<br>
<table class="table table-striped col-md-12" id="reports">
  <thead>
    <tr>
      <th>Building</th>
      <th>Area</th>
      <th>ProblemType</th>
      <th>Emergency Level</th>
      <th>Status</th>
      <th>More Info</th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td>
          <%= report.building %>
        </td>
        <td>
          <%= report.area %>
        </td>
        <td>
          <%= report.problemtype %>
        </td>
        <td>
          <%= report.emergencylevel %>
        </td>
        <td>
          <%= report.status %>
        </td>
        <td>
          <%= link_to "More about", report_path(report)%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<!-- <%= link_to 'Start New Report', new_report_path, :class => 'btn btn-success' %> -->
<%= link_to 'Generate QR Code', qrcode_path, :class => 'btn btn-columbia col-2' %>

app/views/reports/new.html.erb
<h2 class="text-columbia">Create New Report</h2>

<%= form_tag reports_path, :class => 'form', :multipart => true, :id => 'form' do %>
  <%= label :report, :building, 'Location: Building', :class => 'col-form-label' %>
  <%= text_field :report, :building, :value => @prefilled_building, :class => 'form-control' %>
  <%= label :report, :area, 'Location: Area', :class => 'col-form-label' %>
  <%= text_field :report, :area, :value => @prefilled_area, :class => 'form-control' %>
  <%= label :report, :uni, 'Please enter your UNI', :class => 'col-form-label' %>
  <%= text_field :report, :uni, :class => 'form-control' %>
  <%= label :report, :description, 'Description', :class => 'col-form-label' %>
  <%= text_area :report, :description, :class => 'form-control' %>
  <%= label :report, :file, 'Image', :class => 'col-form-label' %>
  <%= file_field :report, :file, :class => 'form-control' %>
  <%= label :report, :problemtype, 'Problem Type', :class => 'col-form-label'%>
  <%= select :report, :problemtype, @problemlist, {}, :class => 'form-control col-3' %>
  <%= label :report, :emergencylevel, 'Emergency Level', :class => 'col-form-label'  %>
  <%= select :report, :emergencylevel, ['Urgent','Ordinary'], {}, :class => 'form-control col-3' %>
  <br/>
  <%= submit_tag 'Publish', :class => 'btn btn-columbia' %>
  <%= link_to 'Cancel', root_path, :class => 'btn btn-secondary' %>
<% end %>

app/views/reports/show.html.erb
<!--  app/views/reports/show.html.erb -->
<h2 class="text-columbia">Specific Details of Issue </h2>

<ul id="details">
  <h2 style="font-size: 22px;">Location: </h2>

  <li style="margin-left: 14px;">
    Building:
    <%= @report.building %>
  </li>
  <li style="margin-left: 14px;">
    Area:
    <%= @report.area %>
  </li>
  <br>
  <h2 style="font-size: 22px;">Problem Information: </h2>
  <li style="margin-left: 14px;">
    Problem Type:
    <%= @report.problemtype %>
  </li>
  <li style="margin-left: 14px;">
    Emergency Level:
    <%= @report.emergencylevel %>
  </li>
  <li style="margin-left: 14px;">
    Description:
    <% if @report.description.blank? %>
    No Description
    <%else %>
    <%= @report.description %>
    <%end%>
  </li>
  <li style="margin-left: 14px;">
    Image:
    <% if @report.file_url.nil? %>
    No Image
    <%else %>
    <%= image_tag @report.file_url, size: '100x100' %>
    <%end%>
  </li>
  <li style="margin-left: 14px;">
    Complete Status:
    <%= @report.status %>
  </li>
  <br>
  <h2 style="font-size: 22px;">Comments: </h2>
  <%@report.comments.all.each do |cmt|%>
    <li style="margin-left: 14px;"> 
      <%= cmt.manager.name%>: <%= cmt.comment%>
    </li>
  <% end %>
  <li style="margin-left: 14px;"> 
    <%= form_tag addcmt_report_path(@report) do %>
      <div class="form-row">
        <%= text_field :comment, :cmt, :class => 'form-control col-sm-5' %>
        <%= submit_tag 'Add Comment', :class => 'btn btn-columbia' %>
      </div>
    <% end %>
  </li>
</ul>

<br>

<div class="row">
  <%= link_to 'Management', edit_report_path(@report), :class => 'btn btn-columbia col-2' %>
  <% if @report.status == "Uncompleted"%>
    <%= link_to 'Mark as Completed', complete_report_path(@report), 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger col-2' %>
  <% else %>
    <div class="btn btn-primary col-2"> Already compeleted </div>
  <% end %>
  <%= link_to 'Back to Report List', reports_path, :class => 'btn btn-columbia col-2' %>
</div>